### ISSUE TITLE
Some vertex names in edge list are not listed in vertex data frame

### ISSUE THREAD

**Issue by jbucholz** [damianobaldan/riverconn#1] opened 2023-02-27 15:42 UTC
I assume this is potentially an error with my input....but I'm wondering if there is some filtering that's missing for my hydroRivers file. The only element of the tutorial code I have changed is that my hydroRivers file does not have "UP_CELLS" but instead has "DIST_UP_KM". I'm not sure these are entirely interchangeable. I am successfully able to make it through the entire tutorial until I try to make the igraph object....then I get the following error.

river_graph <- create_network(network_links, river_net_simplified, outlet)
Error in igraph::graph_from_data_frame(d = full_net_links_df, v = vertices, :
Some vertex names in edge list are not listed in vertex data frame
In addition: Warning message:
In igraph::graph_from_data_frame(d = full_net_links_df, v = vertices, :
In d' NA' elements were replaced with string "NA"

I'm wondering if this is due in part to the fact that "joints" in network_links are not given a barrier id...but when I filter those out I still get an error. Any help appreciated, as I would like to include this package in my next publication

**Comment by damianobaldan** [comment] 2023-02-27 16:15
If you send me the data you used I can have a look. I agree the error
should be caused by a column naming error.


Il giorno lun 27 feb 2023 alle ore 16:42 jbucholz ***@***.***>
ha scritto:

**Comment by damianobaldan** [comment] 2023-03-02 15:21
Issue fixed with tutorial update. Now tutorial uses HydroRivers v1.1.

**Closed by damianobaldan** 2023-03-02 15:21 UTC
