### ISSUE TITLE
Error in function: "create_network"

### ISSUE THREAD

**Issue by GOFerraz** [damianobaldan/riverconn#5] opened 2024-04-18 21:05 UTC
Hello Baldan,

I'm trying to use your "Riverconn" package for some connectivity analysis in Amazonian streams (Brazil).

My database consists of:
- Hydrographic network (HydroSHEDS): hydro_WGS
- Watershed (SNAPP - Venticique (2016)): basin_WGS
- Road crossing points: dam_WGS

**When trying to create the "river_graph" object, the "create_network" function always causes the same problem with the conditional "delta" of the function.** As in the example below:

```
> > river_graph <- create_network(network_links, river_net_simplified, outlet)
> Error in if (delta > 0) { : missing value where TRUE/FALSE required
```
 
I'm sending you a part of the database as an example and, if possible, I'm looking forward to some feedback with possible solutions.

Congratulations on your work and see you!

[Example.zip](https://github.com/damianobaldan/riverconn/files/15030560/Example.zip)

**Comment by damianobaldan** [comment] 2024-04-23 08:46
Hi the issue is in the outlet definition.

use `outlet <- get_outlet(river_net_simplified, shape_basin, distance = 1)` to get the outlet of the catchment and it will work.

This line of code: `outlet <- river_net_simplified$NodeID[river_net_simplified$DIST_DN_KM == 0 ]` looks for the sf record for which the field DIST_DN_KM is equal to zero, that is the outlet of the river in the sea. In case your catchment is a tributary of a bigger stream, it would not work, given the definition of DIST_DN_KM (see hydrosheds documentation for the meaning of this field). 

If you find it confusing, you can save the river_net_simplified shapefile to a file (`sf::st_write()`), and check manually which NodeID field corresponds to the outlet and assign it to the outlet object in the code. 

All the best, 
Damiano

**Closed as completed** 2024-04-23 08:46 UTC
